In [7]:
import pandas as pd

In [8]:
data=pd.read_csv('mobile_phone_data.csv')

In [9]:
data

,Brand,Model,Release Year,Price in(USD),Battery Capacity (mAh),Screen Size (inches),Primary Camera (MP),Storage Options (GB),Processor,RAM (GB),Weight (grams),Operating System,Average Price (USD)
0,Samsung,Galaxy S2,2011,549,1650,4.30,8,"16, 32",Exynos 4210,1.0,116,Android 2.3,729.0
1,Samsung,Galaxy S5,2014,649,2800,5.10,16,"16, 32",Snapdragon 801,2.0,145,Android 4.4,729.0
2,Samsung,Galaxy S8,2017,749,3000,5.80,12,"64, 128",Snapdragon 835,4.0,155,Android 7.0,729.0
3,Samsung,Galaxy S10,2019,899,3400,6.10,12,"128, 512",Snapdragon 855,8.0,157,Android 9.0,729.0
4,Samsung,Galaxy S21,2021,799,4000,6.20,64,"128, 256",Exynos 2100,8.0,169,Android 11,729.0
5,Samsung,Galaxy S23,2023,799,3900,6.10,50,"128, 256, 512",Snapdragon 8 Gen 2,8.0,168,Android 13,729.0
6,Samsung,Galaxy Z Flip 5,2023,999,3700,6.70,12,"256, 512",Snapdragon 8 Gen 2,8.0,187,Android 13,729.0
7,Apple,iPhone 4S,2011,649,1432,3.50,8,"16, 32, 64",Apple A5,0.5,140,iOS 5,729.0
8,Apple,iPhone 6,2014,649,1810,4.70,8,"16, 64, 128",Apple A8,1.0,129,iOS 8,729.0
9,Apple,iPhone X,2017,999,2716,5.80,12,"64, 256",Apple A11 Bionic,3.0,174,iOS 11,729.0
10,Apple,iPhone 12,2020,799,2815,6.10,12,"64, 128, 256",Apple A14 Bionic,4.0,164,iOS 14,729.0
11,Apple,iPhone 14 Pro,2022,999,3200,6.10,48,"128, 256, 512, 1024",Apple A16 Bionic,6.0,206,iOS 16,729.0
12,Apple,iPhone 15,2023,799,3279,6.10,48,"128, 256, 512",Apple A16 Bionic,6.0,171,iOS 17,729.0
13,Apple,iPhone 15 Pro Max,2023,1199,4422,6.70,48,"256, 512, 1024",Apple A17 Pro,8.0,221,iOS 17,729.0
14,Motorola,Droid RAZR,2011,599,1780,4.30,8,16,TI OMAP 4430,1.0,127,Android 2.3,729.0
15,Motorola,Moto G,2013,179,2070,4.50,5,"8, 16",Snapdragon 400,1.0,143,Android 4.3,729.0
16,Motorola,Moto X,2015,399,2300,5.20,13,"16, 32",Snapdragon 801,2.0,144,Android 5.1,729.0
17,Motorola,Moto Z,2016,699,2600,5.50,13,"32, 64",Snapdragon 820,4.0,136,Android 6.0,729.0
18,Motorola,Moto G Stylus,2023,299,5000,6.80,50,"128, 256",MediaTek Helio G88,6.0,195,Android 13,729.0
19,Motorola,Razr 2023,2023,999,3800,6.90,64,"256, 512",Snapdragon 8+ Gen 1,8.0,188,Android 13,729.0
20,Motorola,Edge 40,2023,599,4400,6.55,50,"256, 512",Dimensity 8020,8.0,171,Android 13,729.0

In [10]:
scatter_chart=data.groupby(['Brand','Battery Capacity (mAh)'])['Weight (grams)'].mean().reset_index()
scatter_chart

       Brand  Battery Capacity (mAh)  Weight (grams)
0      Apple                    1432           140.0
1      Apple                    1810           129.0
2      Apple                    2716           174.0
3      Apple                    2815           164.0
4      Apple                    3200           206.0
5      Apple                    3279           171.0
6      Apple                    4422           221.0
7   Motorola                    1780           127.0
8   Motorola                    2070           143.0
9   Motorola                    2300           144.0
10  Motorola                    2600           136.0
11  Motorola                    3800           188.0
12  Motorola                    4400           171.0
13  Motorola                    5000           195.0
14   Samsung                    1650           116.0
15   Samsung                    2800           145.0
16   Samsung                    3000           155.0
17   Samsung                    3400           157.0
18   Samsung                    3700           187.0
19   Samsung                    3900           168.0
20   Samsung                    4000           169.0

In [11]:
scatter_chart2=data.groupby(['Brand','Battery Capacity (mAh)'])['Price in(USD)'].mean().reset_index()
scatter_chart2

       Brand  Battery Capacity (mAh)  Price in(USD)
0      Apple                    1432          649.0
1      Apple                    1810          649.0
2      Apple                    2716          999.0
3      Apple                    2815          799.0
4      Apple                    3200          999.0
5      Apple                    3279          799.0
6      Apple                    4422         1199.0
7   Motorola                    1780          599.0
8   Motorola                    2070          179.0
9   Motorola                    2300          399.0
10  Motorola                    2600          699.0
11  Motorola                    3800          999.0
12  Motorola                    4400          599.0
13  Motorola                    5000          299.0
14   Samsung                    1650          549.0
15   Samsung                    2800          649.0
16   Samsung                    3000          749.0
17   Samsung                    3400          899.0
18   Samsung                    3700          999.0
19   Samsung                    3900          799.0
20   Samsung                    4000          799.0

In [13]:
revenue=pd.read_csv('brand_segment_revenue.csv')
revenue

    Year    Brand                           Segment  Revenue (Billion USD)
0   2012    Apple                            iPhone                  78.60
1   2012    Apple                               Mac                  23.20
2   2012    Apple                              iPad                  30.90
3   2012    Apple                          Services                  12.80
4   2012    Apple  Wearables, Home, and Accessories                  10.70
..   ...      ...                               ...                    ...
83  2015  Samsung                    Display Panels                  24.16
84  2016  Samsung                     Communication                  85.92
85  2016  Samsung              Consumer Electronics                  41.35
86  2016  Samsung                    Semiconductors                  44.97
87  2016  Samsung                    Display Panels                  23.68

[88 rows x 4 columns]

In [14]:
revenue.groupby('Segment')['Revenue (Billion USD)'].mean()

Segment
Communication                        85.806667
Consumer Electronics                 44.288333
Display Panels                       25.230000
Mac                                  25.680000
Products and Systems Integration      4.414286
Semiconductors                       36.298333
Services                             33.170000
Software and Services                 2.857143
Wearables, Home, and Accessories     17.360000
iPad                                 25.060000
iPhone                              133.480000
Name: Revenue (Billion USD), dtype: float64